name = "fleet-immune"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
[[kv_namespaces]]
binding = "IMMUNE_KV"
id = "47f517cca29843958fe8a7bef8010050"
